-- Tabela de Escalas
CREATE TABLE IF NOT EXISTS public.schedules (
  id bigint generated by default as identity primary key,
  user_id bigint references public.app_users(id) on delete cascade,
  date date not null,
  shift text check (shift in ('morning', 'afternoon', 'full')) default 'full',
  store_id bigint references public.stores(id) on delete set null, -- Opcional: escalar para loja específica
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Habilitar RLS
ALTER TABLE public.schedules ENABLE ROW LEVEL SECURITY;

-- Políticas
CREATE POLICY "Leitura pública de escalas" ON public.schedules FOR SELECT USING (true);
CREATE POLICY "Escrita autenticada de escalas" ON public.schedules FOR ALL USING (true) WITH CHECK (true); -- Simplificado para MVP
