-- SQL para criar tabela de usuários simples (sem depender do Supabase Auth complexo)
-- Isso permite criar usuários diretamente pelo painel admin do seu site

CREATE TABLE IF NOT EXISTS public.app_users (
  id bigint generated by default as identity primary key,
  username text not null unique,
  password text not null, -- Em produção real, isso deveria ser hash, mas para MVP interno ok
  email text,
  role text default 'user',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Habilitar segurança básica
ALTER TABLE public.app_users ENABLE ROW LEVEL SECURITY;

-- Política: Todos podem ler (para login funcionar)
CREATE POLICY "Leitura pública de usuários" ON public.app_users FOR SELECT USING (true);

-- Política: Apenas logados podem criar/editar/excluir (ou deixar aberto para seu uso inicial)
CREATE POLICY "Gerenciamento total" ON public.app_users FOR ALL USING (true) WITH CHECK (true);

-- Inserir usuário admin padrão se não existir
INSERT INTO public.app_users (username, password, role)
VALUES ('admin', 'admin123', 'admin')
ON CONFLICT (username) DO NOTHING;
