-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- Create profiles table (extends default auth.users)
create table profiles (
  id uuid references auth.users on delete cascade not null primary key,
  username text unique,
  role text check (role in ('admin', 'manager', 'supervisor', 'tecnico', 'user')) default 'user',
  department text,
  is_technician boolean default false,
  avatar_url text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for profiles
alter table profiles enable row level security;

create policy "Public profiles are viewable by everyone"
  on profiles for select
  using ( true );

create policy "Users can insert their own profile"
  on profiles for insert
  with check ( auth.uid() = id );

create policy "Users can update own profile"
  on profiles for update
  using ( auth.uid() = id );

-- Stores Table
create table stores (
  id bigint generated by default as identity primary key,
  name text not null,
  active boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

alter table stores enable row level security;
create policy "Stores are viewable by everyone" on stores for select using (true);

-- Categories Table
create table categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  active boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

alter table categories enable row level security;
create policy "Categories are viewable by everyone" on categories for select using (true);

-- Tickets Table
create table tickets (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  status text default 'novo' check (status in ('novo', 'em_analise', 'aguardando_peca', 'resolvido', 'nao_resolvido', 'fechado')),
  priority text default 'media' check (priority in ('baixa', 'media', 'alta', 'critica')),
  category_id bigint references categories(id),
  store_id bigint references stores(id),
  requester_id uuid references profiles(id),
  technician_id uuid references profiles(id),
  attachment_url text,
  additional_info text,
  created_at timestamp with time zone default timezone('utc'::text, now()),
  updated_at timestamp with time zone default timezone('utc'::text, now()),
  closed_at timestamp with time zone
);

alter table tickets enable row level security;

-- RLS for Tickets
create policy "Tickets are viewable by everyone (authenticated)"
  on tickets for select
  using ( auth.role() = 'authenticated' );

create policy "Authenticated users can create tickets"
  on tickets for insert
  with check ( auth.role() = 'authenticated' );

create policy "Users can update their own tickets or if they are technicians"
  on tickets for update
  using ( auth.uid() = requester_id or auth.uid() = technician_id );

-- Ticket Events (Timeline)
create table ticket_events (
  id bigint generated by default as identity primary key,
  ticket_id bigint references tickets(id) on delete cascade,
  user_id uuid references profiles(id),
  event_type text not null, -- 'comment', 'status_change', 'assignment'
  description text,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

alter table ticket_events enable row level security;
create policy "Events are viewable by everyone" on ticket_events for select using (true);
create policy "Authenticated users can create events" on ticket_events for insert with check (auth.role() = 'authenticated');

-- Function to handle new user signup
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, username, role, avatar_url)
  values (new.id, new.raw_user_meta_data->>'username', 'user', new.raw_user_meta_data->>'avatar_url');
  return new;
end;
$$ language plpgsql security definer;

-- Trigger for new user signup
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- Insert Mock Data
insert into stores (name) values 
('Loja 1 - Centro'), ('Loja 2 - Shopping'), ('Loja 3 - Norte');

insert into categories (name) values 
('Hardware'), ('Software'), ('Rede'), ('Impressora');
