-- SQL para criar a tabela de lojas e inserir dados iniciais

-- 1. Criar a tabela se não existir
create table if not exists public.stores (
  id bigint generated by default as identity primary key,
  name text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Habilitar RLS (Row Level Security)
alter table public.stores enable row level security;

-- 3. Criar políticas de acesso (leitura pública, escrita apenas autenticados)
create policy "Lojas são visíveis para todos"
  on public.stores for select
  using (true);

create policy "Apenas usuários autenticados podem modificar lojas"
  on public.stores for all
  using (auth.role() = 'authenticated');

-- 4. Inserir as lojas iniciais
insert into public.stores (name) values
  ('GSM1 - LAGOA'),
  ('GSM2 - PRAÇA'),
  ('GSM3 - CONDE'),
  ('GSM4 - IPANEMA'),
  ('GSM5 - COPA'),
  ('GSM6 - BARRAMARES'),
  ('GSM7 - ICARAI'),
  ('GSM8 - RECREIO'),
  ('GSM9 - NOVA IGUAÇU'),
  ('GSM10 - GILKA'),
  ('GSM11 - DARK/SPIRIT'),
  ('GSM12 - NA BRASA RECREIO'),
  ('GSM13 - SB FREGUESIA'),
  ('GSM14 - ABOLIÇÃO'),
  ('GSM15 - VENTANIA'),
  ('GSM16 - SB PEPE'),
  ('GSM17 - MANDALA'),
  ('GSM200 - NA BRASA NI'),
  ('GSM201 - NA BRASA ABOLIÇÃO'),
  ('GSM18 - SB CAXIAS'),
  ('GSM19 - SÃO FRANCISCO'),
  ('GSM20 - BACKER'),
  ('GSM21 - URUGUAI'),
  ('GSM99 - ESCRITORIO'),
  ('GSMDD - FABRICA')
on conflict (id) do nothing; -- Evita erro se rodar duas vezes (assumindo id se tiver, senao name unique seria melhor)
